services:
  # ---------------------------------------------------------------- etcd ---
  etcd:
    image: quay.io/coreos/etcd:v3.5.16
    container_name: milvus-etcd
    restart: unless-stopped
    command: >
      etcd
      -advertise-client-urls=http://0.0.0.0:2379
      -listen-client-urls=http://0.0.0.0:2379
      --data-dir /etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    volumes:
      - ${DATA_ROOT}/etcd:/etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: [milvus_net]

  # ------------------------------------------------------------- MinIO ---
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    restart: unless-stopped
    command: minio server /minio_data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ${DATA_ROOT}/minio:/minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: [milvus_net]

  # ----------------------------------------------------------- Milvus ---
  standalone:
    image: milvusdb/milvus:v2.5.4
    container_name: milvus-standalone
    restart: unless-stopped
    command: ["milvus", "run", "standalone"]
    security_opt: [seccomp:unconfined]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "${MILVUS_PORT}:19530"
      - "${MILVUS_MONITOR_PORT}:9091"
    volumes:
      - ${DATA_ROOT}/milvus:/var/lib/milvus
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: [milvus_net]

  # ------------------------------------------------------------ Backend ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.authors: "Nguyen Trang Sy Lam <nguyentrangsilam@gmail.com>"
        org.opencontainers.image.description: "RAGGIN service"
    image: melukootto/raggin:latest
    container_name: raggin
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    environment:
      OLLAMA_API: ${OLLAMA_API}
      DOWNLOADS_DIR: /downloads
      MODEL_CACHE_DIR: /models/bge-m3
      MILVUS_URI: http://standalone:${MILVUS_PORT}
    depends_on:
      standalone:
        condition: service_healthy
    volumes:
      - ${HOST_DOWNLOADS_DIR}:/downloads
      - ${HOST_MODEL_DIR}:/models/bge-m3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks: [milvus_net]

# ---------------------------------------------------------------- network ---
networks:
  milvus_net:
    name: milvus